export { default as HomePage } from './HomePage.vue'
export { default as AboutPage } from './AboutPage.vue'
export { default as ProjectsPage } from './ProjectsPage.vue'
export { default as ContactPage } from './ContactPage.vue'
export { default as NotFound } from './NotFound.vue'
